# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or newd alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Question.delete_all
Question.create(title:"question 1",difficulties:"easy",category:"ps",content:"If a number between 0 and 11/20 is selected at random, which of the following will the number most likely be between?",answer_1: "0 and 5/20",corr_1:"TRUE",answer_2:"5/20 and 1/4",corr_2:"FALSE",answer_3:"1/4 and 1/3",corr_3:"FALSE",answer_4:"1/3 and 2/5",corr_4:"FALSE",answer_5:"2/5 and 11/20",corr_5:"FALSE")
Question.create(title:"question 2",difficulties:"medium",category:"ps",content:"A store has a sale where all of its clothing is 20 percent to 50 percent off.  A month after the sale begins the store adds an additional discount of 25 percent to the already reduced prices.  If a shirt cost $20 before the sales what is the highest possible price, in dollars, the shirt could have after the two discounts?",answer_1:"12",corr_1:"TRUE",answer_2:"13",corr_2:"FALSE",answer_3:"14",corr_3:"FALSE",answer_4:"15",corr_4:"FALSE",answer_5:"16",corr_5:"FALSE")
Question.create(title:"question 3",difficulties:"medium",category:"ps",content:"What is the sum of the different positive prime factors of 630?",answer_1: "9",corr_1:"FALSE",answer_2:"17",corr_2:"TRUE",answer_3:"20",corr_3:"FALSE",answer_4:"22",corr_4:"FALSE",answer_5:"25",corr_5:"FALSE")
Question.create(title:"question 4",difficulties:"medium",category:"ps",content:"Consider the equation a^3b^2c^3 = 900, where a, b, c are positive numbers and 1 < a < b < c. What is the value of the sum a + b + c?",answer_1:"6",corr_1:"FALSE",answer_2:"10",corr_2:"TRUE",answer_3:"14",corr_3:"FALSE",answer_4:"16",corr_4:"FALSE",answer_5:"20",corr_5:"FALSE")
Question.create(title:"question 5",difficulties:"hard",category:"ps",content:"Tank A is 1/4 full of water and tank B, which has three times the capacity of tank A, is 1/2 full of water.  If all of the water in tank A is poured into tank B, then tank B will be filled to what fraction of its capacity?",answer_1:"5/12",corr_1:"FALSE",answer_2:"3/4",corr_2:"FALSE",answer_3:"2/3",corr_3:"FALSE",answer_4:"7/12",corr_4:"TRUE",answer_5:"9/12",corr_5:"FALSE")
Question.create(title:"question 6",difficulties:"hard",category:"ps",content:"A woman bought 11 books for $110.  If she lost one book, what is the amount, in dollars, for which she would she have to sell the remaining books in order to have a 20 percent profit?",answer_1:"11",corr_1:"FALSE",answer_2:"12",corr_2:"FALSE",answer_3:"12",corr_3:"FALSE",answer_4:"12.6",corr_4:"FALSE",answer_5:"13.2",corr_5:"TRUE")
Question.create(title:"question 7",difficulties:"hard",category:"ps",content: "What is the least positive integer that is divisible by each of the integers 2 through 8, inclusive",answer_1:"210",corr_1:"FALSE",answer_2:"420",corr_2:"FALSE",answer_3:"840",corr_3:"TRUE",answer_4:"1,260",corr_4:"FALSE",answer_5:"5,040",corr_5:"FALSE")
Question.create(title:"question 8",difficulties:"very_hard",category:"ps",content:"On a football team, players are either defensive or offensive.  Before cuts, the ratio of defensive players to offensive players is 1 to 2.  If 2 defensive players are cut from the team and 8 offensive players are cut, the ratio of defensive players to offensive players becomes 2 to 3.  How many players are on the team after the cuts?",answer_1:"12",corr_1:"FALSE",answer_2:"14",corr_2:"FALSE",answer_3:"16",corr_3:"FALSE",answer_4:"18",corr_4:"FALSE",answer_5:"20",corr_5:"TRUE")
Question.create(title:"question 9",difficulties:"very_hard",category:"ps",content:"The surface of a car windshield reflects 15pct of the sunlight and allows all the rest to pass through.  If a reflective shield is put under the windshield that reflects 70pct of the light that strikes it and absorbs all the rest, what percent of the sunlight that strikes the windshield is absorbed by the reflective shield?",answer_1:"3pct",corr_1:"FALSE",answer_2:"7pct",corr_2:"FALSE",answer_3:"25.5pct",corr_3:"TRUE",answer_4:"27pct",corr_4:"FALSE",answer_5:"30pct",corr_5:"FALSE")
Question.create(title:"question 10",difficulties:"very_hard",category:"ps",content: "If 148 is divided by a particular integer, the remainder is 12.  If 723 is divided by the same integer, the remainder is 9. When the sum of 148 and 723 is divided by the same integer, the remainder is 4. The divisor has what value?",answer_1:"12",corr_1:"FALSE",answer_2:"17",corr_2:"TRUE",answer_3:"19",corr_3:"FALSE",answer_4:"25",corr_4:"FALSE",answer_5:"none of these",corr_5:"FALSE")

Question.create(title:"question 11",difficulties:"easy",category:"ds",content:"Joe received x amount of dollars from his job as a salesman and put $500 of it in the bank.  He had no source of income other than his earnings from this job.  What is the value of x ?",ds_1:"Joe spent twice as much money on rent as he put in the bank.",ds_2:"Joe spent 4/5 of his earnings and put the rest in the bank.",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"TRUE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"FALSE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 12",difficulties:"medium",category:"ds",content:"Is the integer x even ?",ds_1:"The sum of x, 2x + 2, and 4x is even .",ds_2:"The sum of x, 11 – 2x, and 4x is odd.",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"FALSE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"TRUE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 13",difficulties:"medium",category:"ds",content:"If s, t, u and v are four integers, are they consecutive integers ?",ds_1:"v = t + 2 and u = s +  2",ds_2:"None of the 4 integers is a multiple of 4.",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"TRUE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"FALSE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 14",difficulties:"medium",category:"ds",content:"What is the value of (x – y)^8?",ds_1:"xy = 1 1",ds_2:"x and y are integers",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"TRUE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 15",difficulties:"hard",category:"ds",content:"What is the remainder when 9^x is divided by 10 ?",ds_1:"x > 5",ds_2:"x is prime",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"TRUE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 16",difficulties:"hard",category:"ds",content:"If R is an integer between 1 and 9, and P – R = 2370, what is the value of R ?",ds_1:"P is divisile by  4",ds_2:"P is divisible by 9",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"TRUE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"FALSE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 17",difficulties:"hard",category:"ds",content:"The positive integers r, s, and t are such that r is divisible by s and s is divisible by t. Is r even ?",ds_1:"st is od d",ds_2:"rt is even",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"TRUE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"FALSE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 18",difficulties:"very_hard",category:"ds",content:"If a sales assistants earns commission of 8pct on every full-price article and 5pct on every on-sale article how much commission did he make in June ?",ds_1:"Total revenue for June was $3,100 .",ds_2:"15pct of his total commission was made from on-sale items.",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"TRUE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 19",difficulties:"very_hard",category:"ds",content:"Is the integer p divisible by  6?",ds_1:"9p is divisible by  6",ds_2:"8p is divisible by 6",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"TRUE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")
Question.create(title:"question 20",difficulties:"very_hard",category:"ds",content:"If k is a positive integer and t is the remainder when 3 + 5k is divided by 4, what is the value of t ?",ds_1:"k – 1 is divisible by 4 .",ds_2:"k > 25",answer_1:"statement (1) BY ITSELF is sufficient, but statement (2) by itself is not.",corr_1:"FALSE",answer_2:"statement (2) BY ITSELF is sufficient, but statement (1) by itself is not.",corr_2:"FALSE",answer_3:"neither statement BY ITSELF is sufficient but the two statements COMBINED are sufficient",corr_3:"TRUE",answer_4:"EACH statement BY ITSELF is sufficient",corr_4:"FALSE",answer_5:"NEITHER statement is sufficient BY ITSELF or COMBINED",corr_5:"FALSE")

puts "all the questions has been loaded"





